build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Flutter
      uses: subito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang cmake ninja-build pkg-config libgtk-3-dev \
          liblzma-dev libstdc++-12-dev librsvg2-bin
    
    - name: Install dependencies
      run: |
        flutter pub get
        dart run build_runner build --delete-conflicting-outputs
    
    - name: Build libwarpdeck
      run: |
        cd ../../libwarpdeck
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
    
    - name: Build Linux app
      run: chmod +x build_scripts/build_linux.sh && ./build_scripts/build_linux.sh
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: warpdeck-linux
        path: |
          build/linux/x64/release/bundle
          build/linux/WarpDeck.AppDir