name: 'Setup Build Environment'
description: 'Sets up Flutter, C++ tools, and dependencies with caching'

inputs:
  platform:
    description: 'Target platform (linux or macos)'
    required: true
  flutter-version:
    description: 'Flutter version to install'
    required: true
    default: '3.22.2'
  cache-key-suffix:
    description: 'Additional suffix for cache keys'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache platform-specific packages
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.platform == 'linux' && '/var/cache/apt' || '/usr/local/Cellar' }}
          ${{ inputs.platform == 'linux' && '/var/lib/apt' || '/usr/local/var/homebrew' }}
        key: ${{ runner.os }}-packages-${{ hashFiles('.github/workflows/**') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-packages-

    - name: Install Linux dependencies
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake build-essential pkg-config libssl-dev \
          libavahi-client-dev libgtk-3-dev ninja-build clang \
          libayatana-appindicator3-dev librsvg2-bin imagemagick

    - name: Install macOS dependencies  
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew install openssl brotli pkg-config

    - name: Setup Flutter with cache
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
        cache: true

    - name: Setup vcpkg with cache
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    - name: Cache vcpkg packages
      uses: actions/cache@v4  
      with:
        path: |
          ${{ inputs.platform == 'linux' && '/usr/share/vcpkg/installed' || '/usr/local/share/vcpkg/installed' }}
          ${{ env.VCPKG_ROOT }}/packages
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json', '**/CMakeLists.txt') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install C++ dependencies
      shell: bash
      run: |
        $VCPKG_ROOT/vcpkg install boost-asio openssl nlohmann-json

    - name: Cache Flutter packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          warpdeck-flutter/warpdeck_gui/.dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install Flutter dependencies
      shell: bash
      run: |
        cd warpdeck-flutter/warpdeck_gui
        flutter pub get