name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.22.2'

jobs:
  test-libwarpdeck:
    name: Test libwarpdeck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          pkg-config \
          libssl-dev \
          libavahi-client-dev \
          valgrind

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install boost-asio openssl nlohmann-json catch2
        cd ..

    - name: Build and test libwarpdeck
      run: |
        cd libwarpdeck
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DBUILD_TESTS=ON \
              ..
        make -j$(nproc)
        
        # Run tests if they exist
        if [ -f "./test_libwarpdeck" ]; then
          ./test_libwarpdeck
        fi

  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest
    needs: test-libwarpdeck
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          pkg-config \
          libssl-dev \
          libavahi-client-dev

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install boost-asio openssl nlohmann-json
        cd ..

    - name: Build libwarpdeck
      run: |
        cd libwarpdeck
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              ..
        make -j$(nproc)
        cd ../..

    - name: Build CLI
      run: |
        cd cli
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              ..
        make -j$(nproc)

    - name: Test CLI basic functionality
      run: |
        cd cli/build
        # Test help command
        ./warpdeck --help || echo "Help command test completed"
        
        # Test config command
        ./warpdeck config --set-name "CI Test Device" || echo "Config command test completed"

  test-flutter:
    name: Test Flutter GUI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          pkg-config \
          libssl-dev \
          libavahi-client-dev \
          libgtk-3-dev \
          ninja-build \
          clang

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install boost-asio openssl nlohmann-json
        cd ..

    - name: Build libwarpdeck
      run: |
        cd libwarpdeck
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              ..
        make -j$(nproc)
        cd ../..

    - name: Test Flutter app
      run: |
        cd warpdeck-flutter/warpdeck_gui
        flutter pub get
        
        # Run dart analysis
        dart analyze
        
        # Run tests if they exist
        if [ -d "test" ]; then
          flutter test
        fi
        
        # Generate FFI bindings
        dart run build_runner build --delete-conflicting-outputs
        
        # Test that the app builds successfully
        flutter build linux --release

  build-quick:
    name: Quick Build Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          pkg-config \
          libssl-dev \
          libavahi-client-dev \
          libgtk-3-dev \
          ninja-build \
          clang

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install boost-asio openssl nlohmann-json
        cd ..

    - name: Quick build test
      run: |
        # Build libwarpdeck
        cd libwarpdeck
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              ..
        make -j$(nproc)
        cd ../..
        
        # Build CLI
        cd cli
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake \
              ..
        make -j$(nproc)
        cd ../..
        
        # Test Flutter dependencies and analysis
        cd warpdeck-flutter/warpdeck_gui
        flutter pub get
        dart analyze
        dart run build_runner build --delete-conflicting-outputs

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Flutter Analysis
      run: |
        cd warpdeck-flutter/warpdeck_gui
        flutter pub get
        dart format --set-exit-if-changed .
        dart analyze --fatal-infos

    - name: Check for TODO/FIXME comments
      run: |
        echo "Checking for TODO/FIXME comments..."
        if grep -r "TODO\|FIXME" --include="*.dart" --include="*.cpp" --include="*.h" . | grep -v ".github"; then
          echo "⚠️  Found TODO/FIXME comments in code"
          exit 0  # Don't fail the build, just warn
        else
          echo "✅ No TODO/FIXME comments found"
        fi